### ISSUE TITLE
Include application integration testing example

### ISSUE THREAD

**Issue by lpil** [nkly/purescript-express#75]
Hello!

Thank you for this library.

I think a file in which the testing of an Express app is shown would be a useful addition to the `examples` directory. Would it be possible to have such an example added? :)

Cheers,
Louis

**Comment by nkly** [comment]
Hi Louis,

Thank you. It is a really good idea :+1:  I'd love to do that, but unfortunately don't have time. I'd be glad to review and assist, though, if you or anybody else implements it.

Best,
Nikolai.

**Comment by lpil** [comment]
I'd be happy to contribute once I've worked out how to test such an application :)

Would you start the server and use a http client to make requests to it?

**Comment by nkly** [comment]
Yes, I would start the server and issue requests. In JS I would use [chai-http](https://github.com/chaijs/chai-http) to automatically start the server on a free port, send requests, receive responses, and make assertions about them. I couldn't find anything like that for PS, but maybe it's possible to use [purescript-node-http](https://github.com/purescript-node/purescript-node-http) to create such a tool.

**Comment by lpil** [comment]
Great, thank you for the pointers

**Comment by lpil** [comment]
I've been trying to implement this and I'm struggling. Here's what I currently have https://gist.github.com/lpil/65bc416f8caa610bbad119419a38a03b

My test fails with no output. Does it look like I'm going the right way here?

**Comment by lpil** [comment]
Hi @nkly. I have it mostly worked with the exception that once the test have finished the process doesn't die as the server is still listening. How do you handle this?

Here's an example of my approach:

```purescript
main = do
  Express.listenHttp Web.app 9876 \_ -> do
    runTest suites

suites = do
  test "GET /" do
    resp <- Affjax.get "http://localhost:9876/"
    Assert.equal (StatusCode 200) resp.status
    Assert.equal resp.response "Hello, world!"
      
```
