### ISSUE TITLE
set raw value to MockRequest

### ISSUE THREAD

**Issue by spocke** [nkly/purescript-express#79]
It would have been nice if there was a way to set a non string as the body value of a MockRequest. I've started using your library and I'm using the json middleware where it parses the body as a foregin json object and in order to test that I need to be able to set the body of the MockRequest to something other than a string I currently kind of hacked around that using unsafeCoerce but that doesn't feel right in case something changes in the underlying code.
```
setBodyValue :: forall a. Encode a => a -> MockRequest -> MockRequest
setBodyValue = setBody <<< unsafeCoerce <<< encode
```

**Comment by nkly** [comment]
Yep, it sounds like a good idea. Would you like to implement it?
