### ISSUE TITLE
Text.Parsing.Parser bombs out on long URLs

### ISSUE THREAD

**Issue by kika** [nkly/purescript-express#80]
The URL is questionable, as it's longer than 2048, but according to the standard, it should support at least 8000. 
It's a `purescript-parsing` problem, not `purescript-express`, but it renders the query string parsing for any _serious_ :-) application useless.

```
Purescript/purescript-express/output/Text.Parsing.Parser.Pos/index.js:21
        var updatePosChar = function (v) {
                                     ^
RangeError: Maximum call stack size exceeded
    at updatePosChar (Purescript/purescript-express/output/Text.Parsing.Parser.Pos/index.js:21:38)
    at Purescript/purescript-express/output/Data.Foldable/foreign.js:22:15
    at Purescript/purescript-express/output/Text.Parsing.Parser.Pos/index.js:47:90
    at Purescript/purescript-express/output/Text.Parsing.Parser.String/index.js:80:129
    at Purescript/purescript-express/output/Control.Monad.State.Class/index.js:23:57
    at Purescript/purescript-express/output/Control.Monad.State.Trans/index.js:193:71
    at Purescript/purescript-express/output/Control.Monad.State.Trans/index.js:104:61
    at Purescript/purescript-express/output/Control.Monad.State.Trans/index.js:104:61
    at Purescript/purescript-express/output/Control.Monad.State.Trans/index.js:106:28
    at Purescript/purescript-express/output/Data.Identity/index.js:151:16
```

example of the query string (very long): `side=F&req={%22name%22:%22R101%22,%22units%22:42,%22width%22:600,%22depth%22:1200,%22devices%22:[{%22libo%22:%22libo-eaba9443de8c3b6c9f4d891b4cdccd691791435759ef0f030a7b568ffb207ecd%22,%22name%22:%22OPSRV001%22,%22position%22:14,%22side%22:%22F%22},{%22libo%22:%22libo-76998523911836dbfab1cef3d139e3d7%22,%22name%22:%22GW001A%22,%22position%22:38,%22side%22:%22F%22},{%22libo%22:%22libo-76998523911836dbfab1cef3d139e3d7%22,%22name%22:%22GW002A%22,%22position%22:36,%22side%22:%22F%22},{%22libo%22:%22libo-e32b502751baa823e6dde2227963ae9f99dc0531b523b94689b29d199f68cf3f%22,%22name%22:%22FLS001%22,%22position%22:17,%22side%22:%22F%22},{%22libo%22:%22libo-7922f29164294c84416f207fec3bcaa22c662bf784333a9c0d1f9dc1b5e41457%22,%22name%22:%22SP001A%22,%22position%22:20,%22side%22:%22F%22},{%22libo%22:%22libo-31ddf2d9e2a64dc14ab87fc99175c5c4e894991260cde4ab11567100c3bf0d5e%22,%22name%22:%22STOR002%22,%22position%22:21,%22side%22:%22F%22},{%22libo%22:%22libo-d7227691c99dc10372f956de8a934ce7addbea027a96b2dea7b4bde1426c3cbb%22,%22name%22:%22CORE001A%22,%22position%22:31,%22side%22:%22F%22},{%22libo%22:%22libo-91eb86b34b2be6544e46341d7d18340d1ab3c0daf1dcb608988d9187cd413643%22,%22name%22:%22STOR004%22,%22position%22:25,%22side%22:%22F%22},{%22libo%22:%22libo-1c8308dded2b7d7745c34fd645a721b598d94185dab280bd3b2c1c2d717b4e0e%22,%22name%22:%22STOR006%22,%22position%22:29,%22side%22:%22F%22},{%22libo%22:%22libo-828dc1ef7731483acc94a0add9bcec5ff1f34a1e6c551b8913f8daa4c124e464%22,%22name%22:%22SW101A%22,%22position%22:42,%22side%22:%22B%22},{%22libo%22:%22libo-828dc1ef7731483acc94a0add9bcec5ff1f34a1e6c551b8913f8daa4c124e464%22,%22name%22:%22SW101B%22,%22position%22:40,%22side%22:%22B%22},{%22libo%22:%22libo-eaba9443de8c3b6c9f4d891b4cdccd691791435759ef0f030a7b568ffb207ecd%22,%22name%22:%22DB001%22,%22position%22:2,%22side%22:%22F%22},{%22libo%22:%22libo-eaba9443de8c3b6c9f4d891b4cdccd691791435759ef0f030a7b568ffb207ecd%22,%22name%22:%22DB002%22,%22position%22:4,%22side%22:%22F%22},{%22libo%22:%22libo-eaba9443de8c3b6c9f4d891b4cdccd691791435759ef0f030a7b568ffb207ecd%22,%22name%22:%22DB003%22,%22position%22:6,%22side%22:%22F%22},{%22libo%22:%22libo-9af43175c9ba0c65a08673684c4cf46e%22,%22name%22:%22C001%22,%22position%22:8,%22side%22:%22F%22},{%22libo%22:%22libo-9af43175c9ba0c65a08673684c4cf46e%22,%22name%22:%22C002%22,%22position%22:10,%22side%22:%22F%22}]}`

**Comment by kika** [comment]
@natefaubion nudged me in the right direction - we don't need to dump `purescript-parsing`, we just need to base `ParserT` on `Free` monad, which offers trampolining. I've started a fix but didn't have enough time to finish. Will try to make something soon.

**Comment by felixSchl** [comment]
I think it just comes down to `run trampoline $ run parser <input>
<parser>` without further changes. Have u considered using
purescript-string-parsers at all? Should be pretry much drop in and more
performant as well.

**Comment by natefaubion** [comment]
Anything that uses a naive state-passing representation is going to blow the stack at some point, `purescript-string-parsers` included.

**Comment by felixSchl** [comment]
I just tested it, and the trampoline approach works even on huge inputs. I tested it with 40000 characters. Granted it took a long time to parse, but no stack was overflown, whereas the trampoline-less version died almost instantly.

Here are the required code changes:

```purescript
parse :: String -> Either String (Array Param)
parse str = case runTrampoline $ runParserT str queryString of
    Left err -> Left $ parseErrorMessage err
    Right result -> Right $ toUnfoldable result

-- TODO: update with a ParserT signature
-- queryString :: Parser String (List Param)
queryString = sepBy param (string "&")

-- TODO: update with a ParserT signature
-- param :: Parser String Param
param = do
    name <- liftM1 (decode <<< fromCharArray) $ some $ satisfy (\s -> s /= '=')
    _ <- string "="
    val  <- liftM1 (decode <<< fromCharArray) $ many $ satisfy (\s -> s /= '&')
    pure $ Param name val
```

**Comment by felixSchl** [comment]
I've created a quick PR for it, you can take it or leave it, but it fixes the problem in the short term.

**Comment by kika** [comment]
I've added a test and submitted a PR to @felixSchl branch. WFM and LGTM.
